# tracker_test: tracker.cpp
#     gcc -o tracker_test tracker.cpp -I.

# CC=gcc
# CFLAGS=-I.

# tracker_test: tracker.o
# 	$(CC) -o tracker_test tracker.o 

# For the test
# all: 
# 	g++ tracker.cpp -o tracker_to_run

all: 
	g++ tracker_test.cpp -o tracker_test_to_run
